# Generated by Django 5.1.7 on 2025-03-12 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_url_1", models.URLField()),
                ("job_url_2", models.URLField(blank=True, null=True)),
                ("job_description", models.TextField()),
                ("user_story", models.TextField()),
                ("generated_resume", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
