# Generated by Django 5.1.7 on 2025-03-12 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resume",
            old_name="job_url_2",
            new_name="target_company_url",
        ),
    ]
