# Generated by Django 5.1.7 on 2025-03-14 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_job_url_2_resume_target_company_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resume",
            old_name="job_url_1",
            new_name="recruitment_notice_url",
        ),
    ]
