# Generated by Django 5.1.7 on 2025-03-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_resume_company_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="company_info",
            field=models.TextField(blank=True, null=True, verbose_name="회사 정보"),
        ),
        migrations.AlterField(
            model_name="resume",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성 시간"),
        ),
        migrations.AlterField(
            model_name="resume",
            name="generated_resume",
            field=models.TextField(max_length=10000, verbose_name="생성된 자기소개서"),
        ),
        migrations.AlterField(
            model_name="resume",
            name="job_description",
            field=models.TextField(verbose_name="채용공고 내용"),
        ),
        migrations.AlterField(
            model_name="resume",
            name="recruitment_notice_url",
            field=models.URLField(verbose_name="채용공고 URL"),
        ),
        migrations.AlterField(
            model_name="resume",
            name="target_company_url",
            field=models.URLField(blank=True, null=True, verbose_name="회사 URL"),
        ),
        migrations.AlterField(
            model_name="resume",
            name="user_story",
            field=models.TextField(verbose_name="사용자 자기소개"),
        ),
    ]
