"""
Django settings for cvfactory_project project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'fallback_secret_key_for_development_if_not_set')

# SECURITY WARNING: don't run with debug turned on in production!
# 환경 변수가 'True' 문자열일 경우 True로, 그 외에는 False로 설정합니다.
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

# ALLOWED_HOSTS는 쉼표로 구분된 문자열로 환경 변수에서 가져와 리스트로 변환합니다.
# 예: DJANGO_ALLOWED_HOSTS="cvfactory.kr,www.cvfactory.kr,localhost"
allowed_hosts_str = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_str.split(',') if host.strip()]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "main",
    "whitenoise",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "cvfactory_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'main/templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "cvfactory_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        # 환경 변수 'DATABASE_URL'을 직접 사용하도록 명시합니다.
        # default 인자는 DATABASE_URL 환경 변수가 없을 때만 사용됩니다.
        default=os.environ.get('DATABASE_URL'),
        conn_max_age=600,
        conn_health_checks=True,
        # Northflank에서 PostgreSQL을 사용할 때 SSL 연결이 필요할 수 있습니다.
        # ssl_require=os.environ.get('DJANGO_DB_SSL_REQUIRE', 'False') == 'True' # 필요시 이 라인 활성화
    )
}

# DATABASE_URL 환경 변수가 비어 있는지 확인하는 로깅 추가 (디버깅용)
if not os.environ.get('DATABASE_URL'):
    print("WARNING: DATABASE_URL environment variable is not set. Using default SQLite.")
else:
    # 실제 운영 환경에서는 전체 URL을 로그에 남기지 않는 것이 보안상 좋습니다.
    # 여기서는 Northflank 환경 변수 주입 확인을 위해 임시로 출력합니다.
    # 실제 배포 시에는 이 print 문을 제거하거나, URL의 일부만 로깅하도록 수정하세요.
    print(f"INFO: Attempting to use DATABASE_URL from environment.")


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "main/static",
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise 설정 (미들웨어 최상단에 추가 필요)
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django가 프록시 뒤에서 실행될 때 X-Forwarded-Host 헤더를 신뢰할지 여부
USE_X_FORWARDED_HOST = True

# Northflank 배포시 필요한 추가 설정 (선택적)
# CSRF_TRUSTED_ORIGINS = [os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', 'http://localhost:8000')] # 예: https://*.cvfactory.kr
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') # Northflank가 리버스 프록시 뒤에 있다면
# SECURE_SSL_REDIRECT = os.environ.get('DJANGO_SECURE_SSL_REDIRECT', 'False') == 'True' # 프로덕션에서 True 권장

# Django가 프록시(예: Northflank) 뒤에서 실행될 때, 
# X-Forwarded-Proto 헤더를 신뢰하여 요청이 HTTPS인지 HTTP인지 결정합니다.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# CSRF 보호를 위해 신뢰할 수 있는 출처를 설정합니다.
# DJANGO_CSRF_TRUSTED_ORIGINS 환경 변수에서 쉼표로 구분된 문자열을 읽어 리스트로 만듭니다.
# 예: DJANGO_CSRF_TRUSTED_ORIGINS="https://cvfactory.dev,https://www.cvfactory.dev"
csrf_trusted_origins_str = os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', 'https://localhost') # 기본값은 실제 서비스에 맞게 조정 필요
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_trusted_origins_str.split(',') if origin.strip()]

# HTTPS로 자동 리디렉션 (프로덕션 환경에서 권장)
# True 또는 False 문자열을 bool 값으로 변환합니다.
SECURE_SSL_REDIRECT = os.environ.get('DJANGO_SECURE_SSL_REDIRECT', 'False') == 'True'
